 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: us.h
 *
 * Description: Header file for the Ultrasonic Sensor driver
 *
 * Author: Omar Tarek Youssef Kamal
 *
 *******************************************************************************/

#ifndef US_H_
#define US_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/* US HW Ports and Pins Ids */
#define US_TRIGGER_PORT_ID                 PORTB_ID
#define US_TRIGGER_PIN_ID                  PIN5_ID

/*
* Description: Just for knowledge
#define US_ECHO_PORT_ID                    PORTD_ID
#define US_ECHO_PIN_ID                     PIN6_ID
*
*/

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

/*
 * Description :
 * 1.Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);



#endif /* US_H_ */
